---
# vars file for yugabyteYBA
yba_host: "https://34.133.13.219:443"
yba_admin_name: "admin"
yba_admin_email: "admin@gmail.com"
yba_admin_password: "Admin123$$$"
yba_environment: "dev"
yba_token_file: "{{ lookup('env','HOME') }}/.yba-api-token"
provider_name: "gcp-provider"
region_name: "south-asia"
zone_name: "mum1"
ssh_user: "ybaadmin"
ssh_key_name: "ybaadmin"
ssh_key_path: "/home/adev4769_gmail_com/id_rsa"
instance_type_name: "db-node-type"
num_cores: 2
mem_size: 10
mount_point: "/mnt/yba-data"
volume_size: 10
volume_type: "SSD"
instance_type: "db-node-type"
nodes:
  - { ip: "10.0.0.12", name: "db-pr-node-1" }
  - { ip: "10.0.0.13", name: "db-pr-node-2" }
  - { ip: "10.0.0.14", name: "db-pr-node-3" }
universe_name: "universe-pr"
yb_version: "2024.2.4.0-b89"
replication_factor: 3
num_nodes: 3
master_gflags: '{"fs_wal_dirs":"/mnt/yba-wal","log_dir":"/mnt/yba-shared","tmp_dir":"/mnt/yba-data/tmp"}'
server_gflags: '{"primary":{"fs_wal_dirs":"/mnt/yba-wal","log_dir":"/mnt/yba-shared","tmp_dir":"/mnt/yba-data/tmp"}}'
