[monitoring]
monitor ansible_host=10.0.0.14 ansible_user=shettyanisha2004_gmail_com

[nodes]
node1 ansible_host=10.0.0.10 ansible_user=shettyanisha2004_gmail_com
node2 ansible_host=10.0.0.11 ansible_user=shettyanisha2004_gmail_com
node3 ansible_host=10.0.0.12 ansible_user=shettyanisha2004_gmail_com