---
- name: Configure system for YugabyteDB on RHEL/CentOS
  hosts: default
  become: yes
  gather_facts: yes

  vars:
    admin_user: ybaadmin
    db_user: yugabyte

    db_uid: 995
    db_gid: 994

    yugabyte_sudoers_file: /etc/sudoers.d/ybaadmin
    core_dump_dir: /home/yugabyte/cores

  tasks:
  # -------------------------------------------------------------------
  # USERS & GROUPS
  # -------------------------------------------------------------------
  - name: Ensure yugabyte group exists with fixed GID
    ansible.builtin.group:
      name: "{{ db_user }}"
      gid: "{{ db_gid }}"
      state: present

  - name: Ensure yugabyte user exists with fixed UID
    ansible.builtin.user:
      name: "{{ db_user }}"
      uid: "{{ db_uid }}"
      group: "{{ db_user }}"
      shell: /sbin/nologin
      create_home: yes
      state: present

  - name: Ensure ybaadmin admin user exists
    ansible.builtin.user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      create_home: yes
      state: present

  - name: Grant passwordless sudo to ybaadmin
    ansible.builtin.copy:
      dest: "{{ yugabyte_sudoers_file }}"
      content: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
      owner: root
      group: root
      mode: '0440'
      validate: 'visudo -cf %s'

  # -------------------------------------------------------------------
  # LIMITS (ULIMITS)
  # -------------------------------------------------------------------


  - name: Check for the ulimit 
    ansible.builtin.command: ulimit -a 
    register: ulimit

  - name: Print the output for ulimit
    ansible.builtin.debug:
      var: ulimit.stdout_lines 
        
  - name: Configure file descriptor and signal limits for yugabyte
    ansible.builtin.blockinfile:
      path: /etc/security/limits.conf
      block: |
        {{ db_user }} soft nofile 1048576
        {{ db_user }} hard nofile 1048576
        {{ db_user }} soft sigpending 119934
        {{ db_user }} hard sigpending 119934
      state: present

  - name: Check for the ulimit after set
    ansible.builtin.command: ulimit -a 
    register: ulimit_set

  - name: Print the output for ulimit
    ansible.builtin.debug:
      var: ulimit_set.stdout_lines 

  - name: Configure nproc limit
    ansible.builtin.lineinfile:
      path: /etc/security/limits.d/20-nproc.conf
      regexp: '^(\*|{{ db_user }})\s+soft\s+nproc'
      line: "* soft nproc 12000"
      state: present
      create: yes

  # -------------------------------------------------------------------
  # CORE DUMPS
  # -------------------------------------------------------------------
  - name: Ensure core dump directory exists
    ansible.builtin.file:
      path: "{{ core_dump_dir }}"
      state: directory
      owner: "{{ db_user }}"
      group: "{{ db_user }}"
      mode: '0755'

  - name: Set vm.swappiness
    ansible.builtin.command: sudo bash -c 'sysctl vm.swappiness=0 >> /etc/sysctl.conf'

  - name: Configure core dump file pattern
    ansible.builtin.command: sudo sysctl kernel.core_pattern=/home/yugabyte/cores/core_%p_%t_%E


  # -------------------------------------------------------------------
  # KERNEL TUNING (SYSCTL)
  # -------------------------------------------------------------------


  - name: Set vm.max_map_count
    ansible.builtin.command: sudo sysctl -w vm.max_map_count=262144

  - name: Set vm.max_map_count_modify
    ansible.builtin.command: sudo bash -c 'sysctl vm.max_map_count=262144 >> /etc/sysctl.conf'

  - name: Set vm.swappiness
    ansible.builtin.command: sysctl vm.max_map_count


  # -------------------------------------------------------------------
  # TRANSPARENT HUGEPAGES (VERIFY ONLY)
  # -------------------------------------------------------------------
  - name: Check Transparent HugePages status
    ansible.builtin.command: cat /sys/kernel/mm/transparent_hugepage/enabled
    register: thp
    changed_when: false

  - name: Print Transparent HugePages status
    ansible.builtin.debug:
      var: thp.stdout_lines
 
  # -------------------------------------------------------------------
  # VALIDATION (IMPORTANT)
  # -------------------------------------------------------------------
  - name: Validate yugabyte user
    ansible.builtin.command: id yugabyte
    changed_when: false

  - name: Validate sysctl values
    ansible.builtin.command: sysctl -a
    changed_when: false
