---
- name: Configure system for YugabyteDB on RHEL/CentOS
  hosts: default
  become: yes
  gather_facts: yes

  vars:
    admin_user: ybaadmin
    db_user: yugabyte

    db_uid: 995
    db_gid: 994

    yugabyte_sudoers_file: /etc/sudoers.d/ybaadmin
    core_dump_dir: /home/yugabyte/cores

  tasks:
  # -------------------------------------------------------------------
  # USERS & GROUPS
  # -------------------------------------------------------------------
  - name: Ensure yugabyte group exists with fixed GID
    ansible.builtin.group:
      name: "{{ db_user }}"
      gid: "{{ db_gid }}"
      state: present

  - name: Ensure yugabyte user exists with fixed UID
    ansible.builtin.user:
      name: "{{ db_user }}"
      uid: "{{ db_uid }}"
      group: "{{ db_user }}"
      shell: /sbin/nologin
      create_home: yes
      state: present

  - name: Ensure ybaadmin admin user exists
    ansible.builtin.user:
      name: "{{ admin_user }}"
      shell: /bin/bash
      create_home: yes
      state: present

  - name: Grant passwordless sudo to ybaadmin
    ansible.builtin.copy:
      dest: "{{ yugabyte_sudoers_file }}"
      content: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
      owner: root
      group: root
      mode: '0440'
      validate: 'visudo -cf %s'

  # -------------------------------------------------------------------
  # LIMITS (ULIMITS)
  # -------------------------------------------------------------------
  - name: Configure file descriptor and signal limits for yugabyte
    ansible.builtin.blockinfile:
      path: /etc/security/limits.conf
      block: |
        {{ db_user }} soft nofile 1048576
        {{ db_user }} hard nofile 1048576
        {{ db_user }} soft sigpending 119934
        {{ db_user }} hard sigpending 119934
      state: present

  - name: Configure nproc limit
    ansible.builtin.lineinfile:
      path: /etc/security/limits.d/20-nproc.conf
      regexp: '^(\*|{{ db_user }})\s+soft\s+nproc'
      line: "* soft nproc 12000"
      state: present
      create: yes

  # -------------------------------------------------------------------
  # CORE DUMPS
  # -------------------------------------------------------------------
  - name: Ensure core dump directory exists
    ansible.builtin.file:
      path: "{{ core_dump_dir }}"
      state: directory
      owner: "{{ db_user }}"
      group: "{{ db_user }}"
      mode: '0755'

  - name: Configure core dump file pattern
    ansible.builtin.sysctl:
      name: kernel.core_pattern
      value: "{{ core_dump_dir }}/core_%p_%t_%E"
      state: present
      reload: yes

  # -------------------------------------------------------------------
  # KERNEL TUNING (SYSCTL)
  # -------------------------------------------------------------------
  - name: Set vm.swappiness
    ansible.builtin.sysctl:
      name: vm.swappiness
      value: "0"
      state: present
      reload: yes

  - name: Set vm.max_map_count
    ansible.builtin.sysctl:
      name: vm.max_map_count
      value: "262144"
      state: present
      reload: yes

  # -------------------------------------------------------------------
  # TRANSPARENT HUGEPAGES (VERIFY ONLY)
  # -------------------------------------------------------------------
  - name: Check Transparent HugePages status
    ansible.builtin.command: cat /sys/kernel/mm/transparent_hugepage/enabled
    register: thp
    changed_when: false

  - name: Print Transparent HugePages status
    ansible.builtin.debug:
      var: thp.stdout_lines

  # -------------------------------------------------------------------
  # VALIDATION
  # -------------------------------------------------------------------
  - name: Validate yugabyte user
    ansible.builtin.command: id yugabyte
    changed_when: false
